config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :reservations

  resources :rooms

  resources :room_types

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :room
  belongs_to :user
  has_one :reservation_priority
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.user = current_user

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:room_id, :user_id, :reserve_from, :reserve_upto, :reservation_details, :status)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_for @reservation, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :reserve_from, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select :reserve_from, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :reserve_upto, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select :reserve_upto, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :reservation_details, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :reservation_details, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :status, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :status, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  reservations_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<%- model_class = Reservation -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Reservation %></h1>
</div>
<%= render :partial => 'form' %>

app/views/reservations/index.html.erb
<%- model_class = Reservation -%>
<div class="page-header">
  <h1><%=t '.title', :default => Reservation %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:reserve_from) %></th>
      <th><%= model_class.human_attribute_name(:reserve_upto) %></th>
      <th><%= model_class.human_attribute_name(:reservation_details) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.id %></td>
        <td><%= reservation.reserve_from %></td>
        <td><%= reservation.reserve_upto %></td>
        <td><%= reservation.reservation_details %></td>
        <td><%= reservation.status %></td>
        <td><%=l reservation.created_at, format: :long %></td>
        <td>
          <%= link_to reservation_path(reservation), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to reservation_path(reservation), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_reservation_path,
            :class => 'btn btn-primary' %>

app/views/reservations/new.html.erb
<%- model_class = Reservation -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Reservation %></h1>
</div>
<%= render :partial => 'form' %>

app/views/reservations/show.html.erb
<%- model_class = Reservation -%>
<div class="page-header">
  <h1><%=t '.title', :default => Reservation %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:reserve_from) %></dt>
      <dd><pre class="prettyprint"><%= @reservation.reserve_from %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:reserve_upto) %></dt>
      <dd><pre class="prettyprint"><%= @reservation.reserve_upto %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:reservation_details) %></dt>
      <dd><pre class="prettyprint"><%= @reservation.reservation_details %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:status) %></dt>
      <dd><pre class="prettyprint"><%= @reservation.status %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              reservations_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_reservation_path(@reservation), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              reservation_path(@reservation),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>